version: "3"
services:
  nginx:
    image:nginx:stable-alpine
    ports:
      - "80:80"
  meu-node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js
